# Usando uma imagem base do Python
FROM python:3.12-slim

# Configurar variáveis de ambiente para evitar prompts interativos
ENV PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive

# Atualizar o sistema e instalar dependências necessárias
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    libpq-dev \
    unixodbc \
    unixodbc-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Criar um diretório de trabalho para o projeto
WORKDIR /dbt


# Copiar o arquivo requirements.txt para o contêiner
COPY requirements.txt /requirements.txt

# Instalar as dependências do Python
RUN pip install -r /requirements.txt

# Copiar os arquivos do projeto dbt para o contêiner
COPY . .

# Definir o ENTRYPOINT para usar o comando dbt
ENTRYPOINT ["dbt"]
